[project]
name = 'PyONDE'
dynamic = ['version','authors','description','urls']
requires-python = ">= 3.8"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
	    "Development Status :: 3 - Alpha"
	    ]

#[project.scripts]
#example_script = "PyONDE.bin.example_script:main"

[build-system]
requires = ["setuptools>=64","numpy","h5py","setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Note: With recent setuptools we can use "version_file" instead of "write_to"
write_to = "PyONDE/_version.py"